#web:
#  build: .
#  command: php -S 0.0.0.0:8000 -t /app/public
#  links:
#    - db
#  ports:
#    - "8000:8000"
#  volumes:
#    - .:/app
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: library
